
export enum ContractStatus {
  Active = 'Active',       // 履约中
  Expiring = 'Expiring',   // 即将到期
  Terminated = 'Terminated', // 已退租
  Pending = 'Pending',     // 签约中
  Expired = 'Expired',     // 已到期(历史合同)
}

export enum UnitStatus {
  Vacant = 'Vacant',       // 空置
  Occupied = 'Occupied',   // 已租
  Reserved = 'Reserved',   // 预留
}

export enum DepositStatus {
  Unpaid = 'Unpaid',
  Paid = 'Paid',
  Refunded = 'Refunded',
  Deducted = 'Deducted', // 抵扣
}

export type PaymentCycle = 'Monthly' | 'Quarterly' | 'SemiAnnual' | 'Annual';

export interface RentFreePeriod {
  start: string;
  end: string;
  description: string;
}

export interface Unit {
  id: string;
  name: string; // e.g., 101, 102
  area: number;
  status: UnitStatus;
  floor: number;
  isSelfUse?: boolean;
}

export interface Building {
  id: string;
  name: string; // e.g., 1号楼
  units: Unit[];
}

export interface KeyMoment {
  id: string;
  date: string; // YYYY-MM-DD or YYYY-MM
  title: string;
  description: string;
  type: 'Anniversary' | 'Product' | 'News' | 'Award' | 'Other' | 'ParkAnniversary';
  sourceUrl?: string;
  isAutoGenerated?: boolean;
}

export interface Tenant {
  id: string;
  rootId?: string; // 根ID，用于关联同一个客户的历史续签记录
  name: string;
  contactInfo?: string;
  industry?: string;
  
  // Basic Info for Insights
  foundingDate?: string; // YYYY-MM-DD
  legalRepName?: string; // 法人/管理层姓名
  legalRepBirthday?: string; // MM-DD or YYYY-MM-DD
  contactName?: string; // 对接人姓名
  contactBirthday?: string; // MM-DD or YYYY-MM-DD

  // Link to Asset
  buildingId: string;
  unitIds: string[]; 
  totalArea: number;

  // Lease Terms
  leaseStart: string;
  leaseEnd: string;
  
  // Rent
  unitPrice?: number; // Price per sqm per DAY
  monthlyRent: number; // Total monthly rent (calculated)
  
  rentFreePeriods: RentFreePeriod[];

  // Payment Terms
  paymentCycle: PaymentCycle;
  firstPaymentDate: string;
  firstPaymentMonths?: number;
  
  // Deposit
  depositAmount: number;
  depositStatus: DepositStatus;

  // Termination
  status: ContractStatus;
  terminationDate?: string;
  terminationType?: 'Normal' | 'Early';
  terminationReason?: string;
  
  // Special requirements
  specialRequirements?: string;
  
  // Risk Management
  isRisk?: boolean; // High risk flag

  // New: Parking
  // parkingSpaces field is deprecated in favor of specific fields below, but kept for legacy type safety if needed
  parkingSpaces?: number; 
  
  contractParkingSpaces?: number; // Contracted/Agreed number of spaces
  actualParkingSpaces?: number;   // Actually activated/paid spaces

  parkingUnitPrice?: number; // Price per space per month

  // New: Customer Insights
  keyMoments?: KeyMoment[];
}

export interface PaymentRecord {
  id: string;
  tenantId: string;
  tenantName: string;
  amount: number;
  type: 'Rent' | 'Deposit' | 'ManagementFee' | 'ParkingFee' | 'Other' | 'DepositToRent' | 'DepositRefund'; // Added ParkingFee
  date: string;
  status: 'Received' | 'Pending';
  remarks?: string;
}

export interface MonthlyTrend {
  month: string;
  occupancyRate: number;
  revenueTarget: number;
  revenueCollected: number;
  avgUnitPrice: number; // Average Rent Unit Price (Daily)
}

export interface BillingDetail {
  tenantId: string;
  tenantName: string;
  unitIds: string[];
  amountDue: number;
  amountPaid: number;
  status: 'Paid' | 'Unpaid' | 'Partial' | 'Overdue';
}

export interface ParkingStatDetail {
  tenantId: string;
  tenantName: string;
  contractCount: number;
  actualCount: number;
  // Revenue details removed as requested
}

export interface BudgetAssumption {
  id: string;
  targetType: 'Vacancy' | 'Renewal' | 'RiskTermination' | 'Existing'; 
  targetId: string; // Unit ID or Tenant ID
  targetName: string; // Unit Name or Tenant Name
  
  // Strategy for Expiring/Risk Tenants
  strategy?: 'Renewal' | 'ReLease'; // Renewal=Continue, ReLease=Terminate & Find New
  
  // For Risk Tenants
  projectedTerminationDate?: string; // When do we expect them to leave?

  // For Re-lease / Vacancy / Risk Replacement
  vacancyGapMonths?: number; // Months empty before new tenant
  projectedSignDate: string; // Estimated start date (auto-calc based on gap usually)
  projectedUnitPrice: number; // Estimated Daily Price
  projectedRentFreeMonths: number; // Estimated rent free months

  // For Existing Contracts (Settings)
  priceAdjustment?: {
      startDate: string;
      endDate: string;
      newUnitPrice: number;
  };
  paymentShift?: {
      amount: number;
      fromYear: number;
      fromMonth: number; // 0-11
      toYear: number;
      toMonth: number;   // 0-11
      isActive: boolean;
  };
}

export interface BudgetAdjustment {
  id: string;
  tenantId: string;
  tenantName: string;
  originalYear: number;
  originalMonth: number; // 0-11
  adjustedYear: number;
  adjustedMonth: number; // 0-11
  amount: number;
  reason: string; // e.g., "Pre-payment for next year", "Deferred payment"
}

export interface BudgetAnalysisData {
    occupancy: string;
    revenue: string;
    execution?: string; // New field for Budget vs Actual analysis
}

export interface CloudConfig {
    supabaseUrl: string;
    supabaseKey: string;
    autoSync: boolean;
    projectId: string; // Identifier for this park's data
}

export interface CloudBackupMetadata {
    id: string;
    created_at: string;
    note?: string;
}

export interface BudgetScenario {
    id: string;
    name: string;
    description?: string;
    createdAt: string;
    isActive: boolean; // Indicates if this is the one currently affecting the Dashboard
    
    // The Rules
    assumptions: BudgetAssumption[];
    adjustments: BudgetAdjustment[];
    
    // The Snapshot (Business state at the time of creation)
    // Optional: if not present, uses current live data
    baseDataSnapshot?: {
        tenants: Tenant[];
        buildings: Building[];
    };
}

export interface DashboardData {
  buildings: Building[];
  tenants: Tenant[];
  payments: PaymentRecord[];
  
  // Computed metrics (Current Selected Year)
  totalArea: number;
  leasedArea: number;
  occupancyRate: number;
  
  // Financials (Current Selected Year)
  annualRevenueTarget: number;
  annualRevenueCollected: number;
  annualOccupancyTarget: number;
  
  monthlyRevenueTarget: number;
  monthlyRevenueCollected: number;
  collectionRate: number;

  newContractsCount: number;
  expiringSoonCount: number;

  // New: Yearly Targets Map
  // Key: Year (e.g., 2024), Value: Targets
  yearlyTargets?: Record<number, { revenue: number, occupancy: number }>;

  // Visual/List data
  recentSignings: Tenant[];
  expiringSoon: Tenant[];
  monthlyTrends: MonthlyTrend[];
  prevYearMonthlyTrends?: MonthlyTrend[]; // New: YoY Analysis
  currentMonthBilling: BillingDetail[];

  // New: Parking Stats
  parkingStats: {
      totalContractSpaces: number;
      totalActualSpaces: number;
      totalMonthlyRevenue: number; // Based on Actual
      details: ParkingStatDetail[];
  };

  // New: Budget Management
  budgetAssumptions: BudgetAssumption[];
  budgetAdjustments: BudgetAdjustment[];
  budgetAnalysis: BudgetAnalysisData;
  budgetScenarios?: BudgetScenario[]; // New: Multiple scenarios
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}
