



import React, { useState } from 'react';
import { Tenant, KeyMoment } from '../types';
import { searchTenantInsights } from '../services/geminiService';
import { Sparkles, Calendar, ExternalLink, Search, Globe, Award, Megaphone, Clock, Building2, Loader2, RefreshCw, Briefcase, User, Phone, Cake, ArrowLeft, Flag } from 'lucide-react';

interface TenantInsightsProps {
  tenants: Tenant[];
  onUpdateTenants: (tenants: Tenant[]) => void;
}

export const TenantInsights: React.FC<TenantInsightsProps> = ({ tenants, onUpdateTenants }) => {
  const [selectedTenantId, setSelectedTenantId] = useState<string>(tenants[0]?.id || '');
  const [isSearching, setIsSearching] = useState(false);
  const [batchProgress, setBatchProgress] = useState<{current: number, total: number} | null>(null);
  const [searchFilter, setSearchFilter] = useState('');
  
  // Mobile view state: true = list view, false = detail view
  const [showMobileList, setShowMobileList] = useState(true);

  const selectedTenant = tenants.find(t => t.id === selectedTenantId);
  const filteredTenants = tenants.filter(t => t.name.toLowerCase().includes(searchFilter.toLowerCase()));

  const handleTenantSelect = (id: string) => {
      setSelectedTenantId(id);
      setShowMobileList(false); // Switch to detail view on mobile
  };

  const handleBatchCollect = async () => {
      if (filteredTenants.length === 0) return;
      
      setIsSearching(true);
      setBatchProgress({ current: 0, total: filteredTenants.length });
      
      let updatedTenantsList = [...tenants];
      let processedCount = 0;

      // Process sequentially to avoid rate limits
      for (const tenant of filteredTenants) {
          try {
              const result = await searchTenantInsights(tenant.name);
              
              const tenantIndex = updatedTenantsList.findIndex(t => t.id === tenant.id);
              if (tenantIndex !== -1) {
                  const t = updatedTenantsList[tenantIndex];
                  updatedTenantsList[tenantIndex] = {
                      ...t,
                      keyMoments: result.moments,
                      foundingDate: t.foundingDate || result.foundingDate || t.foundingDate,
                      industry: t.industry || result.industry || t.industry // Auto-fill Industry
                  };
              }
          } catch (e) {
              console.error(`Failed to collect for ${tenant.name}`, e);
          }
          processedCount++;
          setBatchProgress({ current: processedCount, total: filteredTenants.length });
      }

      onUpdateTenants(updatedTenantsList);
      setIsSearching(false);
      setBatchProgress(null);
  };

  const getIconForType = (type: KeyMoment['type'] | 'ParkAnniversary') => {
    switch (type) {
      case 'Anniversary': return <Calendar className="text-rose-500" size={18} />;
      case 'Product': return <Megaphone className="text-blue-500" size={18} />;
      case 'Award': return <Award className="text-amber-500" size={18} />;
      case 'News': return <Globe className="text-indigo-500" size={18} />;
      case 'ParkAnniversary': return <Flag className="text-emerald-500" size={18} />;
      default: return <Clock className="text-slate-400" size={18} />;
    }
  };

  const getTypeLabel = (type: KeyMoment['type'] | 'ParkAnniversary') => {
      const map: Record<string, string> = {
          'Anniversary': '司庆/成立',
          'Product': '产品发布',
          'Award': '荣誉奖项',
          'News': '重大新闻',
          'ParkAnniversary': '入园纪念',
          'Other': '其他动态'
      };
      return map[type] || type;
  };

  // Helper: Calculate Duration in Park
  const calculateParkDuration = (startDate: string) => {
      if (!startDate) return '未开始';
      const start = new Date(startDate);
      const now = new Date();
      const diffTime = Math.abs(now.getTime() - start.getTime());
      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24)); 
      
      const years = Math.floor(diffDays / 365);
      const days = diffDays % 365;
      
      if (years > 0) return `${years}年 ${days}天`;
      return `${days}天`;
  };

  // Helper: Generate Park Anniversary Moments dynamically based on leaseStart
  const generateParkMoments = (tenant: Tenant): (KeyMoment & { isAutoGenerated?: boolean })[] => {
      if (!tenant.leaseStart) return [];
      
      const moments: (KeyMoment & { isAutoGenerated?: boolean })[] = [];
      const start = new Date(tenant.leaseStart);
      const now = new Date();
      const currentYear = now.getFullYear();
      const startYear = start.getFullYear();

      // Start Date Moment
      moments.push({
          id: `park_start_${tenant.id}`,
          date: tenant.leaseStart,
          title: '正式入驻园区',
          description: `签约入驻 ${tenant.unitIds.length} 个单元，开启合作旅程。`,
          type: 'ParkAnniversary', // Custom mapped type
          isAutoGenerated: true
      } as any);

      // Yearly Anniversaries
      for (let year = startYear + 1; year <= currentYear + 1; year++) {
          const anniversaryDate = new Date(start);
          anniversaryDate.setFullYear(year);
          const dateStr = anniversaryDate.toISOString().split('T')[0];
          
          // Only show up to current time + 1 year forecast
          // Calculate which anniversary it is
          const nth = year - startYear;
          
          if (nth > 0) {
              moments.push({
                  id: `park_anniversary_${tenant.id}_${year}`,
                  date: dateStr,
                  title: `入园 ${nth} 周年纪念`,
                  description: `感谢陪伴！${tenant.name} 加入园区已满 ${nth} 周年。`,
                  type: 'ParkAnniversary',
                  isAutoGenerated: true
              } as any);
          }
      }
      return moments;
  };

  // Combine stored moments with generated park moments
  const allMoments = selectedTenant 
      ? [...(selectedTenant.keyMoments || []), ...generateParkMoments(selectedTenant)].sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime())
      : [];

  return (
    <div className="flex flex-col md:flex-row h-[calc(100vh-140px)] gap-6">
      {/* Sidebar List */}
      <div className={`
          w-full md:w-1/4 bg-white rounded-xl border border-slate-200 shadow-sm flex-col overflow-hidden
          ${showMobileList ? 'flex' : 'hidden md:flex'}
      `}>
        <div className="p-4 border-b border-slate-100">
            <h3 className="font-bold text-slate-800 mb-3 flex items-center gap-2">
                <Building2 size={18} /> 客户列表
            </h3>
            <div className="relative mb-3">
                <Search className="absolute left-3 top-2.5 text-slate-400 w-4 h-4" />
                <input 
                    type="text" 
                    placeholder="搜索客户..."
                    value={searchFilter}
                    onChange={e => setSearchFilter(e.target.value)}
                    className="w-full pl-9 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-100"
                />
            </div>
            
            <button 
                onClick={handleBatchCollect}
                disabled={isSearching || filteredTenants.length === 0}
                className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-violet-600 to-indigo-600 text-white px-3 py-2 rounded-lg text-xs font-medium shadow hover:shadow-md disabled:opacity-70 disabled:cursor-wait"
            >
                {isSearching ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
                {isSearching ? `搜集中... ${batchProgress?.current}/${batchProgress?.total}` : '批量搜集所有客户 (AI)'}
            </button>
            {isSearching && batchProgress && (
                <div className="w-full bg-slate-100 h-1 mt-2 rounded-full overflow-hidden">
                    <div 
                        className="bg-violet-500 h-full transition-all duration-300" 
                        style={{width: `${(batchProgress.current / batchProgress.total) * 100}%`}}
                    ></div>
                </div>
            )}
        </div>
        <div className="flex-1 overflow-y-auto p-2 space-y-1">
            {filteredTenants.map(t => (
                <button
                    key={t.id}
                    onClick={() => handleTenantSelect(t.id)}
                    className={`w-full text-left px-4 py-3 rounded-lg text-sm transition-colors flex items-center justify-between ${selectedTenantId === t.id ? 'bg-blue-50 text-blue-700 font-medium' : 'text-slate-600 hover:bg-slate-50'}`}
                >
                    <span className="truncate">{t.name}</span>
                    {t.keyMoments && t.keyMoments.length > 0 && (
                        <span className="bg-blue-100 text-blue-600 text-[10px] px-1.5 py-0.5 rounded-full">{t.keyMoments.length}</span>
                    )}
                </button>
            ))}
        </div>
      </div>

      {/* Main Content */}
      <div className={`
          flex-1 bg-white rounded-xl border border-slate-200 shadow-sm flex-col overflow-hidden
          ${!showMobileList ? 'flex' : 'hidden md:flex'}
      `}>
         {selectedTenant ? (
             <>
                {/* Mobile Back Header */}
                <div className="md:hidden p-3 border-b border-slate-100 flex items-center gap-2 bg-slate-50 text-slate-600">
                    <button onClick={() => setShowMobileList(true)} className="p-2 -ml-1 hover:bg-slate-200 rounded-lg">
                        <ArrowLeft size={18} />
                    </button>
                    <span className="font-bold text-sm">返回客户列表</span>
                </div>

                {/* Header */}
                <div className="p-4 md:p-6 border-b border-slate-100 bg-slate-50/50">
                    <div className="flex justify-between items-start mb-4">
                         <div>
                            <h2 className="text-xl md:text-2xl font-bold text-slate-800">{selectedTenant.name}</h2>
                            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-xs md:text-sm text-slate-500 mt-2">
                                <span className="flex items-center gap-1"><Building2 size={14}/> 租赁: {selectedTenant.unitIds.length} 单元</span>
                                <span className="w-px h-3 bg-slate-300 hidden md:inline"></span>
                                <span>面积: {selectedTenant.totalArea} ㎡</span>
                            </div>
                         </div>
                    </div>

                    {/* Basic Info Card */}
                    <div className="bg-white p-3 md:p-4 rounded-lg border border-slate-200 shadow-sm grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4">
                        <div>
                            <p className="text-xs text-slate-400 mb-1 flex items-center gap-1"><Calendar size={12}/> 成立日期</p>
                            <p className="font-medium text-slate-700 text-sm md:text-base">{selectedTenant.foundingDate || '未录入'}</p>
                        </div>
                        <div>
                            <p className="text-xs text-slate-400 mb-1 flex items-center gap-1"><Flag size={12}/> 累计入园</p>
                            <p className="font-medium text-emerald-600 text-sm md:text-base">{calculateParkDuration(selectedTenant.leaseStart)}</p>
                        </div>
                        <div>
                            <p className="text-xs text-slate-400 mb-1 flex items-center gap-1"><User size={12}/> 法人/高管</p>
                            <div className="flex flex-col">
                                <span className="font-medium text-slate-700 text-sm md:text-base">{selectedTenant.legalRepName || '未录入'}</span>
                                {selectedTenant.legalRepBirthday && <span className="text-xs text-pink-500 flex items-center gap-0.5"><Cake size={10}/> {selectedTenant.legalRepBirthday}</span>}
                            </div>
                        </div>
                        <div>
                            <p className="text-xs text-slate-400 mb-1 flex items-center gap-1"><Briefcase size={12}/> 所属行业</p>
                            <p className="font-medium text-slate-700 text-sm md:text-base">{selectedTenant.industry || '未录入'}</p>
                        </div>
                    </div>
                </div>

                {/* Timeline Content */}
                <div className="flex-1 overflow-y-auto p-4 md:p-10 bg-slate-50">
                    {allMoments.length > 0 ? (
                        <div className="max-w-3xl mx-auto relative">
                            {/* Vertical Line */}
                            <div className="absolute left-6 md:left-8 top-0 bottom-0 w-0.5 bg-slate-200"></div>

                            <div className="space-y-6 md:space-y-8">
                                {allMoments.map((moment, idx) => (
                                    <div key={moment.id} className="relative flex gap-4 md:gap-6 animate-in slide-in-from-bottom-4 duration-500" style={{animationDelay: `${idx * 100}ms`}}>
                                        {/* Icon Node */}
                                        <div className="relative z-10 w-12 h-12 md:w-16 md:h-16 flex-shrink-0 flex flex-col items-center">
                                            <div className={`w-12 h-12 md:w-16 md:h-16 rounded-full bg-white border-4 flex items-center justify-center shadow-sm ${moment.type === 'ParkAnniversary' ? 'border-emerald-100' : 'border-slate-100'}`}>
                                                {getIconForType(moment.type as any)}
                                            </div>
                                        </div>
                                        
                                        {/* Content Card */}
                                        <div className={`flex-1 bg-white p-4 md:p-5 rounded-xl border shadow-sm hover:shadow-md transition-shadow relative
                                            ${moment.type === 'ParkAnniversary' ? 'border-emerald-100 bg-emerald-50/10' : 'border-slate-200'}
                                        `}>
                                            {/* Arrow */}
                                            <div className={`absolute top-4 md:top-6 -left-2 w-4 h-4 bg-white border-l border-b transform rotate-45 ${moment.type === 'ParkAnniversary' ? 'border-emerald-100' : 'border-slate-200'}`}></div>
                                            
                                            <div className="flex justify-between items-start mb-2">
                                                <span className={`text-[10px] px-2 py-0.5 rounded uppercase font-bold tracking-wider
                                                    ${moment.type === 'Anniversary' ? 'bg-rose-50 text-rose-600' : 
                                                      moment.type === 'Product' ? 'bg-blue-50 text-blue-600' :
                                                      moment.type === 'News' ? 'bg-indigo-50 text-indigo-600' :
                                                      moment.type === 'ParkAnniversary' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-600'
                                                    }`}>
                                                    {getTypeLabel(moment.type as any)}
                                                </span>
                                                <span className="text-xs md:text-sm font-mono text-slate-400 font-medium">{moment.date}</span>
                                            </div>
                                            
                                            <h4 className="text-base md:text-lg font-bold text-slate-800 mb-2">{moment.title}</h4>
                                            <p className="text-slate-600 text-xs md:text-sm leading-relaxed mb-3">
                                                {moment.description}
                                            </p>
                                            
                                            {moment.sourceUrl && (
                                                <a 
                                                    href={moment.sourceUrl} 
                                                    target="_blank" 
                                                    rel="noopener noreferrer"
                                                    className="inline-flex items-center gap-1 text-xs text-blue-500 hover:text-blue-700 hover:underline mt-1"
                                                >
                                                    <ExternalLink size={12} /> 查看来源
                                                </a>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>
                            
                            <div className="text-center mt-12 mb-6">
                                <span className="text-slate-400 text-xs bg-slate-100 px-3 py-1 rounded-full">更多历史数据需进一步搜索</span>
                            </div>
                        </div>
                    ) : (
                        <div className="flex flex-col items-center justify-center h-full text-slate-400">
                            <div className="w-20 h-20 md:w-24 md:h-24 bg-slate-100 rounded-full flex items-center justify-center mb-6">
                                <Search size={40} className="text-slate-300" />
                            </div>
                            <h3 className="text-lg font-medium text-slate-600 mb-2">暂无关键时刻数据</h3>
                            <p className="max-w-md text-center text-sm mb-8 px-4">
                                点击列表上方的 <span className="font-bold text-violet-600">"批量搜集"</span> 按钮，AI 助手将自动全网检索客户的成立纪念日、产品发布及重大新闻。
                            </p>
                        </div>
                    )}
                </div>
             </>
         ) : (
             <div className="flex items-center justify-center h-full text-slate-400 p-6 text-center">
                 请选择左侧客户以查看详情
             </div>
         )}
      </div>
    </div>
  );
};
